### ISSUE TITLE
ObjectFilter NameFilter with '<>SomeValue*'

### ISSUE THREAD

**Issue by mitrov** [jhoek/UncommonSense.Nav.Automation#18]
For some reason the -NameFilter doesn't work when having the combination of NOT and a wildcard.

For instance I want to exclude all objects with name 'Free*'
 -NameFilter '<>Free'
... this is not working

But this filter works:
-NameFilter 'Free*'

**Comment by mitrov** [comment]
For some reason browser swallows the * in the box... see title

**Comment by jhoek** [comment]
That "some reason" is probably called MarkDown. ;-p

**Comment by mitrov** [comment]
you are probably right.. drives me nuts ;-)

**Comment by jhoek** [comment]
Click the 'Markdown supported' link anywhere in GitHub for more info. I have become a big Markdown fan. :-)

**Comment by jhoek** [comment]
What I do (or rather - what Thad's library does) is pass on these filters to NAV. I don't think these filters would work in NAV either? But you could always take the output from Get-NAVApplicationObjectInfo and pass it through Where-Object to apply filters? Then you can use wildcards, regular expressions, even entire scripts to filter to your heart's content. :-)

**Comment by jhoek** [comment]
Dzoka wrote: This filter actually works in NAV. It's not a big deal. – I understand your workaround. Maybe it's an encoding thing where the '*' has to be a different character.

**Comment by jhoek** [comment]
Looks like I learned something about NAV today. ;-)

**Comment by mitrov** [comment]
Closing this issue because it's not worth the effort to investigate any further. Workaround with Where-Object in powershell.
